### PR TITLE
Add SQLOperationType to QueryFn for improved introspection.

### PR DESCRIPTION
**Pull request by seandstewart**
I use this library in my day-to-day work and I'm looking to automate some additional bootstrapping I do for managing my query library. Having introspection into the operation type of each function would be extremely helpful!

### CODE REVIEW

**Comment by seandstewart** [comment]
@nackjicholson Any thoughts on this change?

**Comment by nackjicholson** [comment]
Hey @seandstewart thanks for the pull request. Can you expand on how you use this and what make it extremely helpful? I'm just curious, The change itself looks pretty straight forward. I haven't looke at this project in a while. Do you think it makes sense to add any tests or documentation changes for this?

**Comment by seandstewart** [comment]
Hey @nackjicholson -

Thanks for taking a look at this PR! I'm working on a library that will use aiosql and my own serdes library, [typical](https://github.com/seandstewart/typical). In it, I'm adding an abstraction layer that will associate a data model (e.g., a dataclass or named tuple or something similar) with a given aiosql query library. It will also do the connection management piece. As you can imagine, that means we need introspection into the query operation type to understand exactly how to bootstrap the method.

Here's a sample of what I'm doing currently:

My bootstrapping function:

```python

def bootstrap(cls: Type[protos.ServiceProtocol[_T]], func: QueryFn):
    scalar = isscalar(cls, func)
    bulk = not scalar and isbulk(func)
    if func.__name__.endswith("_cursor"):
        run_query = _bootstrap_cursor(func, scalar)

    elif ispersist(func):
        run_query = _bootstrap_persist(func, scalar, bulk)

    else:
        run_query = _bootstrap_default(func, scalar, bulk)

    run_query.__name__ = func.__name__
    run_query.__doc__ = func.__doc__
    run_query.__qualname__ = f"{cls.__name__}.{func.__name__}"
    run_query.__module__ = cls.__module__
    return run_query
```

My support code for detecting the type of operation:

```python

def isbulk(func: QueryFn):
    fname = func.__name__
    return "bulk" in fname or "all" in fname or "select(" in inspect.getsource(func)


def isscalar(cls: Type[protos.ServiceProtocol[_T]], func: QueryFn):
    return func.__name__ in cls.metadata.__scalar_queries__


def ispersist(func: QueryFn):
    sql = func.sql.lower()
    return "insert" in sql or "update" in sql

```

There are a couple problems with this approach which are solved more-readily by having access to the operation type:

1. I'm doing some hand-waving to determine whether this is a "bulk" return (i.e., multiple rows returned) vs a single row return.
2. In order to determine that the return value is "scalar" (i.e., I don't need to convert the return value into the model) I have to completely rely upon user configuration.

With access to the operation-type, I don't need either of these things. My support code becomes:

```python

def isbulk(func: QueryFn):
    return func.operation in _BULK_QUERIES


def isscalar(func: QueryFn):
    return func.operation in _SCALAR_QUERIES


def ispersist(func: QueryFn):
    # This one doesn't change, but that's because of implementation details with the ending function signature.
    sql = func.sql.lower()
    return "insert" in sql or "update" in sql


_SCALAR_QUERIES = {
    SQLOperationType.SELECT_VALUE, 
    SQLOperationType.INSERT_UPDATE_DELETE,
    SQLOperationType.INSERT_UPDATE_DELETE_MANY, 
    SQLOperationType.SCRIPT
}
_BULK_QUERIES = {SQLOperationType.SELECT}
```

I'm not sure an added test is necessary, but I'll look at updating any existing tests and docs to include this change.

**Comment by nackjicholson** [comment]
Wow, I'm very interested in this. You may or may not know that I put in a poorly considered `record_class` feature in aiosql's api to usher results from queries into namedtuples, data classes, pedantic, etc. I undocumented it and deprecated it precisely because I thought it was an overreach for aiosql and might be better done by another library. Sounds like you're building it! 😁 That is great to see, looking forward to learning more. 

Since the whole python world is moving toward stricter static typing I also recently thought about adding an option to produce templated code with Jinja or mako, instead of a dynamic Queries class. The flow being, write sql, have a tool that watches sql dir for file changes and writes real type annotated python code out.

Anyway, really excited to hear that you're building on top. When you have a link, send it my way. I'm keen to learn more and help if I am able

**Comment by nackjicholson** [comment]
@seandstewart Let me know if you do want to add anymore to this PR for tests/docs but I'm comfortable approving.

Sorry Travisci.org seems to have quit running my builds. I'll check things manually (and likely use this as a reason to fi
explore GitHub actions)

**Comment by seandstewart** [comment]
> The flow being, write sql, have a tool that watches sql dir for file changes and writes real type annotated python code out.

Really interesting idea, @nackjicholson - I'll have to keep an out out for this!

I'm glad you're interested in this work, I'll make sure to link you to the library when I put it on GH - I'm still in fleshing things out but I think a prototype is pretty close. I did come across the deprecated record class code and I do agree, the simplicity of aiosql's focus really lets it shine.

I looked into adding or updating a test for this change, but I didn't see any specifically testing the query function output, so I couldn't think of a natural place to test it. I did add a blurb to the documentation about it, however.

**Review by nackjicholson — APPROVED** [review]
:checkered_flag:

**Pull request merged**
