### PR TITLE
Dev

### PR DESCRIPTION
**Pull request by zx80**
WIP

### CODE REVIEW

**Comment by cofin** [comment]
@zx80, I've not had a chance to clean up some of the current work;  to the extent it helps any of the work you are doing now, I have an `[asnycmy](https://github.com/GoogleCloudPlatform/database-assessment/blob/main/src/dma/lib/db/adapters/asyncmy.py)` adapter that may be useful.  that I've not 100% tested, but works for the use case I had.  I'll have the `aiodbc` and the `oracle` adapters tested soon as well.

**Comment by zx80** [comment]
> @zx80, I've not had a chance to clean up some of the current work, so there'd not been a PR for this; to the extent it helps any of the work you are doing now, I have an [asnycmy](https://github.com/GoogleCloudPlatform/database-assessment/blob/main/src/dma/lib/db/adapters/asyncmy.py) adapter that may be useful. that I've not 100% tested, but works for the use case I had. I'll have the `aiodbc` and the `oracle` adapters tested soon as well.

Great! Thanks in advance for this and  the future reports!
In passing, if you could also test the PEP249 drivers with MS SQL et Oracle with the default adapters (which rely on paramstyle) that would be very nice!

**Comment by zx80** [comment]
@cofin would you consider contributing (some/all) of these adapters to aiosql, maybe?

**Comment by cofin** [comment]
> @cofin would you consider contributing (some/all) of these adapters to aiosql, maybe?

I'm totally fine with this.  This is basically the process that led to the current DuckDB adapter.  I also plan to create a Spanner and BigQuery adapter as time permits (if that would be ok?)

**Comment by zx80** [comment]
> > @cofin would you consider contributing (some/all) of these adapters to aiosql, maybe?
> 
> @zx80 I'm totally fine with this. This is basically the process that led to the current DuckDB adapter. I also plan to create a Spanner and BigQuery adapter as time permits (if that would be ok?)

:+1:  :smiley:

**Comment by cofin** [comment]
@zx80 I'll wait until you've finished your updates here before making more changes.  However, I did propose one change that's really a minor "nit".  Feel free to merge or not.  Thanks again!

**Pull request merged**
