### PR TITLE
Add query filename info so that goto-definition works in editors

### PR DESCRIPTION
**Pull request by abo-abo**
Great project. The only thing that was missing for me currently was goto-definition.

Editors can use `fn.__code__.co_filename` to implement goto-definition.

With this change, goto-definition for a query function will go to that function's SQL file, in case the function was created with `aiosql.from_path`.

### CODE REVIEW

**Comment by nackjicholson** [comment]
@abo-abo Thank you, thank you, a thousand times. Thank you! This was one of the things I felt was missing too and I had no idea how to make it happen.

**Comment by zx80** [comment]
I'm trying to make the CI work on #132.

Would it make sense to try to get the line number as well?

**Comment by nackjicholson** [comment]
> Would it make sense to try to get the line number as well?

@zx80 Yeah, it would be even better IMO.

**Comment by abo-abo** [comment]
> Thank you, thank you, a thousand times. Thank you! This was one of the things I felt was missing too and I had no idea how to make it happen.

Glad to see that it works for you. I don't know if static-based goto-definition could work, but REPL-based is good enough for me.

> Also, thanks for all your contributions to the Emacs ecosystem! I benefit everyday from elisp you've written.

You're welcome! I'm happy it's useful.

@zx80 Thanks for fixing the PR!

**Comment by zx80** [comment]
Merged after some fixes to get through the CI, see #132.

A possible follow up would be to get the lineno as well.

**Pull request closed without merging**
