### PR TITLE
Remove usage of cursor in DuckDB

### PR DESCRIPTION
**Pull request by maver1ck**
This fixes:
https://github.com/nackjicholson/aiosql/issues/203

Cursor in DuckDB is new connection. All registered objects are lost. So I'm avoiding usage of cursor.

### CODE REVIEW

**Comment by zx80** [comment]
Hmmm… For some reason all duckdb tests fail but with Python 3.13. Could you look into it?

**Comment by maver1ck** [comment]
@zx80 
Yes. I will check this on Monday.

**Comment by zx80** [comment]
> @zx80 Yes. I will check this on Monday.

Note that as _DuckDB_ could not be installed with python 3.13 on Github CI, there is a condition to skip its installation in `pyproject.toml`, so really it failed with every version where it tried to run.

**Comment by maver1ck** [comment]
@zx80 
Got it. I think it is imposible to eliminate usage of cursor in test cases.

I'll try to prepare new PR where disabling connection cloning (aka. cursor) in DuckDB is optional.
Closing this one.

**Pull request closed without merging**
